### ISSUE TITLE
Units of breakpoints

### ISSUE THREAD

**Issue by karolisgrinkevicius** [jxnblk/styled-system#248]
Since I upgraded the version to 3 of `styled-system` I see inconsistencies among deprecated `responsiveStyle` and `style` utility. Image the following breakpoints defined by the theme:

```js
[ 480, 768, 992, 1200, 1550 ]
```

How to make it work with `pixels` and not `em`s? Because from now on I see media queries are rendered without any units like:

```css
@media screen and (min-width:480) {
  .myElement {
    text-align: left;
  }
}
```
