### ISSUE TITLE
system-components: Responsive styles from theme not correctly applied (?)

### ISSUE THREAD

**Issue by ronnyhaase** [jxnblk/styled-system#263]
Hi!
I think system-components is not applying responsive styles (arrays) from the theme correctly, but I might be mistaken regarding the source of error...

Here's what's going on:

**theme.js**
```js
export default theme = {
  maxWidths: {
    container: ['none', 540, 720, 960, 1140]
  }
}
```
**container.js**
```js
const Container = system({
  mx: 'auto',
  width: 1,
  maxWidth: 'container'
}
```
Get's "compiled" to:
```css
.lnaQeW {
    margin-left: auto;
    margin-right: auto;
    width: 100%;
    max-width: none,540,720,960,1140;
}
```

So the theme read works, but the array is simply put in as string.

This works perfectly fine, just mentioning:
**container.js**
```js
const Container = system({
  mx: 'auto',
  width: 1,
  maxWidth: ['none', 540, 720, 960, 1140]
}
```
